// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgStartFeed } from "./types/oracle/tx";
import { MsgEditFeed } from "./types/oracle/tx";
import { MsgCreateFeed } from "./types/oracle/tx";
import { MsgPauseFeed } from "./types/oracle/tx";

import { FeedEntry as typeFeedEntry} from "./types"
import { Feed as typeFeed} from "./types"
import { FeedValue as typeFeedValue} from "./types"
import { FeedContext as typeFeedContext} from "./types"

export { MsgStartFeed, MsgEditFeed, MsgCreateFeed, MsgPauseFeed };

type sendMsgStartFeedParams = {
  value: MsgStartFeed,
  fee?: StdFee,
  memo?: string
};

type sendMsgEditFeedParams = {
  value: MsgEditFeed,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateFeedParams = {
  value: MsgCreateFeed,
  fee?: StdFee,
  memo?: string
};

type sendMsgPauseFeedParams = {
  value: MsgPauseFeed,
  fee?: StdFee,
  memo?: string
};


type msgStartFeedParams = {
  value: MsgStartFeed,
};

type msgEditFeedParams = {
  value: MsgEditFeed,
};

type msgCreateFeedParams = {
  value: MsgCreateFeed,
};

type msgPauseFeedParams = {
  value: MsgPauseFeed,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgStartFeed({ value, fee, memo }: sendMsgStartFeedParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgStartFeed: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgStartFeed({ value: MsgStartFeed.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgStartFeed: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgEditFeed({ value, fee, memo }: sendMsgEditFeedParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgEditFeed: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgEditFeed({ value: MsgEditFeed.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgEditFeed: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateFeed({ value, fee, memo }: sendMsgCreateFeedParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateFeed: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateFeed({ value: MsgCreateFeed.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateFeed: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgPauseFeed({ value, fee, memo }: sendMsgPauseFeedParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgPauseFeed: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgPauseFeed({ value: MsgPauseFeed.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgPauseFeed: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgStartFeed({ value }: msgStartFeedParams): EncodeObject {
			try {
				return { typeUrl: "/irismod.oracle.MsgStartFeed", value: MsgStartFeed.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgStartFeed: Could not create message: ' + e.message)
			}
		},
		
		msgEditFeed({ value }: msgEditFeedParams): EncodeObject {
			try {
				return { typeUrl: "/irismod.oracle.MsgEditFeed", value: MsgEditFeed.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgEditFeed: Could not create message: ' + e.message)
			}
		},
		
		msgCreateFeed({ value }: msgCreateFeedParams): EncodeObject {
			try {
				return { typeUrl: "/irismod.oracle.MsgCreateFeed", value: MsgCreateFeed.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateFeed: Could not create message: ' + e.message)
			}
		},
		
		msgPauseFeed({ value }: msgPauseFeedParams): EncodeObject {
			try {
				return { typeUrl: "/irismod.oracle.MsgPauseFeed", value: MsgPauseFeed.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgPauseFeed: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						FeedEntry: getStructure(typeFeedEntry.fromPartial({})),
						Feed: getStructure(typeFeed.fromPartial({})),
						FeedValue: getStructure(typeFeedValue.fromPartial({})),
						FeedContext: getStructure(typeFeedContext.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			IrismodOracle: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;