// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: guardian/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QuerySupersRequest is request type for the Query/Supers RPC method
type QuerySupersRequest struct {
	// pagination defines an optional pagination for the request
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QuerySupersRequest) Reset()         { *m = QuerySupersRequest{} }
func (m *QuerySupersRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySupersRequest) ProtoMessage()    {}
func (*QuerySupersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20cf24f8e5be2110, []int{0}
}
func (m *QuerySupersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySupersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySupersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySupersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySupersRequest.Merge(m, src)
}
func (m *QuerySupersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySupersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySupersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySupersRequest proto.InternalMessageInfo

func (m *QuerySupersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QuerySupersResponse is response type for the Query/Supers RPC method
type QuerySupersResponse struct {
	Supers     []Super             `protobuf:"bytes,1,rep,name=supers,proto3" json:"supers"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QuerySupersResponse) Reset()         { *m = QuerySupersResponse{} }
func (m *QuerySupersResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySupersResponse) ProtoMessage()    {}
func (*QuerySupersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20cf24f8e5be2110, []int{1}
}
func (m *QuerySupersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySupersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySupersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySupersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySupersResponse.Merge(m, src)
}
func (m *QuerySupersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySupersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySupersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySupersResponse proto.InternalMessageInfo

func (m *QuerySupersResponse) GetSupers() []Super {
	if m != nil {
		return m.Supers
	}
	return nil
}

func (m *QuerySupersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QuerySupersRequest)(nil), "GridIron.guardian.QuerySupersRequest")
	proto.RegisterType((*QuerySupersResponse)(nil), "GridIron.guardian.QuerySupersResponse")
}

func init() { proto.RegisterFile("guardian/query.proto", fileDescriptor_20cf24f8e5be2110) }

var fileDescriptor_20cf24f8e5be2110 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x3d, 0x4f, 0x3a, 0x31,
	0x1c, 0xc7, 0xaf, 0xfc, 0xff, 0x32, 0x94, 0xc5, 0x54, 0x12, 0xc8, 0xc5, 0x9c, 0x84, 0xf8, 0x40,
	0x1c, 0xda, 0x80, 0x31, 0xee, 0x0c, 0xba, 0x0a, 0x6e, 0xc6, 0xa5, 0x07, 0xb5, 0x5e, 0x84, 0xfb,
	0x1d, 0xd7, 0x9e, 0x84, 0xcd, 0xf8, 0x0a, 0x4c, 0x8c, 0xef, 0x89, 0x91, 0xc4, 0xc5, 0xc9, 0x18,
	0xf0, 0x85, 0x98, 0x6b, 0x8f, 0x27, 0x19, 0xd8, 0x9a, 0xfe, 0x3e, 0xdf, 0x87, 0xf6, 0x87, 0x8b,
	0x32, 0xe1, 0x71, 0x37, 0xe0, 0x21, 0x1b, 0x24, 0x22, 0x1e, 0xd1, 0x28, 0x06, 0x0d, 0x64, 0xf7,
	0x3e, 0x89, 0x47, 0x0f, 0x89, 0x4f, 0xe7, 0x53, 0xb7, 0x28, 0x41, 0x82, 0x19, 0xb2, 0xf4, 0x64,
	0x39, 0xb7, 0xb4, 0x50, 0xcf, 0x0f, 0xd9, 0x60, 0x5f, 0x02, 0xc8, 0x9e, 0x60, 0x3c, 0x0a, 0x18,
	0x0f, 0x43, 0xd0, 0x5c, 0x07, 0x10, 0xaa, 0x6c, 0x7a, 0xda, 0x01, 0xd5, 0x07, 0xc5, 0x7c, 0xae,
	0x84, 0xcd, 0x65, 0x4f, 0x75, 0x5f, 0x68, 0x5e, 0x67, 0x11, 0x97, 0x41, 0x68, 0x60, 0xcb, 0x56,
	0xef, 0x30, 0x69, 0xa5, 0xc4, 0x4d, 0x12, 0x89, 0x58, 0xb5, 0xc5, 0x20, 0x11, 0x4a, 0x93, 0x4b,
	0x8c, 0x97, 0x64, 0x19, 0x55, 0x50, 0xad, 0xd0, 0x38, 0xa6, 0xd6, 0x96, 0xa6, 0xb6, 0xd4, 0x3e,
	0x27, 0xb3, 0xa5, 0xd7, 0x5c, 0x8a, 0x4c, 0xdb, 0x5e, 0x51, 0x56, 0xdf, 0x11, 0xde, 0x5b, 0xb3,
	0x57, 0x11, 0x84, 0x4a, 0x90, 0x73, 0x9c, 0x57, 0xe6, 0xa6, 0x8c, 0x2a, 0xff, 0x6a, 0x85, 0x46,
	0x89, 0xfe, 0xfd, 0x11, 0x6a, 0x14, 0xcd, 0xff, 0xe3, 0xaf, 0x03, 0xa7, 0x9d, 0xc1, 0xe4, 0x6a,
	0xad, 0x56, 0xce, 0xd4, 0x3a, 0xd9, 0x5a, 0xcb, 0x66, 0xae, 0xf6, 0x6a, 0x3c, 0x23, 0xbc, 0x63,
	0x7a, 0x91, 0x21, 0xce, 0xdb, 0x6e, 0xe4, 0x70, 0xb3, 0xc3, 0xe6, 0xcf, 0xb8, 0x47, 0x5b, 0x28,
	0x1b, 0x56, 0xad, 0xbc, 0x7c, 0xfc, 0xbc, 0xe5, 0x5c, 0x52, 0x66, 0x19, 0xbe, 0xd8, 0x20, 0xb3,
	0x6f, 0x69, 0xb6, 0xc6, 0x53, 0x0f, 0x4d, 0xa6, 0x1e, 0xfa, 0x9e, 0x7a, 0xe8, 0x75, 0xe6, 0x39,
	0x93, 0x99, 0xe7, 0x7c, 0xce, 0x3c, 0xe7, 0xf6, 0x42, 0x06, 0x3a, 0x0d, 0xe8, 0x40, 0x9f, 0x69,
	0xa1, 0x14, 0xc4, 0xa1, 0xd0, 0x43, 0x88, 0x1f, 0x17, 0x5e, 0x7d, 0xe8, 0x26, 0x3d, 0xa1, 0x96,
	0x9e, 0x7a, 0x14, 0x09, 0xe5, 0xe7, 0xcd, 0x4a, 0xcf, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x90,
	0xf6, 0xb9, 0x06, 0x75, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Supers returns all Supers
	Supers(ctx context.Context, in *QuerySupersRequest, opts ...grpc.CallOption) (*QuerySupersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Supers(ctx context.Context, in *QuerySupersRequest, opts ...grpc.CallOption) (*QuerySupersResponse, error) {
	out := new(QuerySupersResponse)
	err := c.cc.Invoke(ctx, "/GridIron.guardian.Query/Supers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Supers returns all Supers
	Supers(context.Context, *QuerySupersRequest) (*QuerySupersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Supers(ctx context.Context, req *QuerySupersRequest) (*QuerySupersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Supers not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Supers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySupersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Supers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GridIron.guardian.Query/Supers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Supers(ctx, req.(*QuerySupersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GridIron.guardian.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Supers",
			Handler:    _Query_Supers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guardian/query.proto",
}

func (m *QuerySupersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySupersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySupersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySupersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySupersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySupersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Supers) > 0 {
		for iNdEx := len(m.Supers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Supers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QuerySupersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySupersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Supers) > 0 {
		for _, e := range m.Supers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QuerySupersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySupersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySupersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySupersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySupersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySupersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Supers = append(m.Supers, Super{})
			if err := m.Supers[len(m.Supers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
