// Generated by Ignite ignite.com/cli
import { Registry } from '@cosmjs/proto-signing'
import { IgniteClient } from "./client";
import { MissingWalletError } from "./helpers";
import { Module as CosmosAuthV1Beta1, msgTypes as CosmosAuthV1Beta1MsgTypes } from './cosmos.auth.v1beta1'
import { Module as CosmosAuthzV1Beta1, msgTypes as CosmosAuthzV1Beta1MsgTypes } from './cosmos.authz.v1beta1'
import { Module as CosmosBankV1Beta1, msgTypes as CosmosBankV1Beta1MsgTypes } from './cosmos.bank.v1beta1'
import { Module as CosmosBaseTendermintV1Beta1, msgTypes as CosmosBaseTendermintV1Beta1MsgTypes } from './cosmos.base.tendermint.v1beta1'
import { Module as CosmosCrisisV1Beta1, msgTypes as CosmosCrisisV1Beta1MsgTypes } from './cosmos.crisis.v1beta1'
import { Module as CosmosDistributionV1Beta1, msgTypes as CosmosDistributionV1Beta1MsgTypes } from './cosmos.distribution.v1beta1'
import { Module as CosmosEvidenceV1Beta1, msgTypes as CosmosEvidenceV1Beta1MsgTypes } from './cosmos.evidence.v1beta1'
import { Module as CosmosFeegrantV1Beta1, msgTypes as CosmosFeegrantV1Beta1MsgTypes } from './cosmos.feegrant.v1beta1'
import { Module as CosmosGovV1, msgTypes as CosmosGovV1MsgTypes } from './cosmos.gov.v1'
import { Module as CosmosGovV1Beta1, msgTypes as CosmosGovV1Beta1MsgTypes } from './cosmos.gov.v1beta1'
import { Module as CosmosNftV1Beta1, msgTypes as CosmosNftV1Beta1MsgTypes } from './cosmos.nft.v1beta1'
import { Module as CosmosParamsV1Beta1, msgTypes as CosmosParamsV1Beta1MsgTypes } from './cosmos.params.v1beta1'
import { Module as CosmosSlashingV1Beta1, msgTypes as CosmosSlashingV1Beta1MsgTypes } from './cosmos.slashing.v1beta1'
import { Module as CosmosStakingV1Beta1, msgTypes as CosmosStakingV1Beta1MsgTypes } from './cosmos.staking.v1beta1'
import { Module as CosmosTxV1Beta1, msgTypes as CosmosTxV1Beta1MsgTypes } from './cosmos.tx.v1beta1'
import { Module as CosmosUpgradeV1Beta1, msgTypes as CosmosUpgradeV1Beta1MsgTypes } from './cosmos.upgrade.v1beta1'
import { Module as CosmosVestingV1Beta1, msgTypes as CosmosVestingV1Beta1MsgTypes } from './cosmos.vesting.v1beta1'
import { Module as IbcApplicationsInterchainAccountsControllerV1, msgTypes as IbcApplicationsInterchainAccountsControllerV1MsgTypes } from './ibc.applications.interchain_accounts.controller.v1'
import { Module as IbcApplicationsInterchainAccountsHostV1, msgTypes as IbcApplicationsInterchainAccountsHostV1MsgTypes } from './ibc.applications.interchain_accounts.host.v1'
import { Module as IbcApplicationsTransferV1, msgTypes as IbcApplicationsTransferV1MsgTypes } from './ibc.applications.transfer.v1'
import { Module as IbcCoreChannelV1, msgTypes as IbcCoreChannelV1MsgTypes } from './ibc.core.channel.v1'
import { Module as IbcCoreClientV1, msgTypes as IbcCoreClientV1MsgTypes } from './ibc.core.client.v1'
import { Module as IbcCoreConnectionV1, msgTypes as IbcCoreConnectionV1MsgTypes } from './ibc.core.connection.v1'
import { Module as IrismodCoinswap, msgTypes as IrismodCoinswapMsgTypes } from './irismod.coinswap'
import { Module as IrismodFarm, msgTypes as IrismodFarmMsgTypes } from './irismod.farm'
import { Module as IrismodHtlc, msgTypes as IrismodHtlcMsgTypes } from './irismod.htlc'
import { Module as IrismodMt, msgTypes as IrismodMtMsgTypes } from './irismod.mt'
import { Module as IrismodOracle, msgTypes as IrismodOracleMsgTypes } from './irismod.oracle'
import { Module as IrismodRandom, msgTypes as IrismodRandomMsgTypes } from './irismod.random'
import { Module as IrismodRecord, msgTypes as IrismodRecordMsgTypes } from './irismod.record'
import { Module as IrismodService, msgTypes as IrismodServiceMsgTypes } from './irismod.service'
import { Module as IrismodToken, msgTypes as IrismodTokenMsgTypes } from './irismod.token'
import { Module as PetrihubGuardian, msgTypes as PetrihubGuardianMsgTypes } from './petrihub.guardian'
import { Module as PetrihubMint, msgTypes as PetrihubMintMsgTypes } from './petrihub.mint'
import { Module as TibcAppsMtTransferV1, msgTypes as TibcAppsMtTransferV1MsgTypes } from './tibc.apps.mt_transfer.v1'
import { Module as TibcAppsNftTransferV1, msgTypes as TibcAppsNftTransferV1MsgTypes } from './tibc.apps.nft_transfer.v1'
import { Module as TibcCoreClientV1, msgTypes as TibcCoreClientV1MsgTypes } from './tibc.core.client.v1'
import { Module as TibcCorePacketV1, msgTypes as TibcCorePacketV1MsgTypes } from './tibc.core.packet.v1'
import { Module as TibcCoreRoutingV1, msgTypes as TibcCoreRoutingV1MsgTypes } from './tibc.core.routing.v1'


const Client = IgniteClient.plugin([
    CosmosAuthV1Beta1, CosmosAuthzV1Beta1, CosmosBankV1Beta1, CosmosBaseTendermintV1Beta1, CosmosCrisisV1Beta1, CosmosDistributionV1Beta1, CosmosEvidenceV1Beta1, CosmosFeegrantV1Beta1, CosmosGovV1, CosmosGovV1Beta1, CosmosNftV1Beta1, CosmosParamsV1Beta1, CosmosSlashingV1Beta1, CosmosStakingV1Beta1, CosmosTxV1Beta1, CosmosUpgradeV1Beta1, CosmosVestingV1Beta1, IbcApplicationsInterchainAccountsControllerV1, IbcApplicationsInterchainAccountsHostV1, IbcApplicationsTransferV1, IbcCoreChannelV1, IbcCoreClientV1, IbcCoreConnectionV1, IrismodCoinswap, IrismodFarm, IrismodHtlc, IrismodMt, IrismodOracle, IrismodRandom, IrismodRecord, IrismodService, IrismodToken, PetrihubGuardian, PetrihubMint, TibcAppsMtTransferV1, TibcAppsNftTransferV1, TibcCoreClientV1, TibcCorePacketV1, TibcCoreRoutingV1
]);

const registry = new Registry([
  ...CosmosAuthV1Beta1MsgTypes,
  ...CosmosAuthzV1Beta1MsgTypes,
  ...CosmosBankV1Beta1MsgTypes,
  ...CosmosBaseTendermintV1Beta1MsgTypes,
  ...CosmosCrisisV1Beta1MsgTypes,
  ...CosmosDistributionV1Beta1MsgTypes,
  ...CosmosEvidenceV1Beta1MsgTypes,
  ...CosmosFeegrantV1Beta1MsgTypes,
  ...CosmosGovV1MsgTypes,
  ...CosmosGovV1Beta1MsgTypes,
  ...CosmosNftV1Beta1MsgTypes,
  ...CosmosParamsV1Beta1MsgTypes,
  ...CosmosSlashingV1Beta1MsgTypes,
  ...CosmosStakingV1Beta1MsgTypes,
  ...CosmosTxV1Beta1MsgTypes,
  ...CosmosUpgradeV1Beta1MsgTypes,
  ...CosmosVestingV1Beta1MsgTypes,
  ...IbcApplicationsInterchainAccountsControllerV1MsgTypes,
  ...IbcApplicationsInterchainAccountsHostV1MsgTypes,
  ...IbcApplicationsTransferV1MsgTypes,
  ...IbcCoreChannelV1MsgTypes,
  ...IbcCoreClientV1MsgTypes,
  ...IbcCoreConnectionV1MsgTypes,
  ...IrismodCoinswapMsgTypes,
  ...IrismodFarmMsgTypes,
  ...IrismodHtlcMsgTypes,
  ...IrismodMtMsgTypes,
  ...IrismodOracleMsgTypes,
  ...IrismodRandomMsgTypes,
  ...IrismodRecordMsgTypes,
  ...IrismodServiceMsgTypes,
  ...IrismodTokenMsgTypes,
  ...PetrihubGuardianMsgTypes,
  ...PetrihubMintMsgTypes,
  ...TibcAppsMtTransferV1MsgTypes,
  ...TibcAppsNftTransferV1MsgTypes,
  ...TibcCoreClientV1MsgTypes,
  ...TibcCorePacketV1MsgTypes,
  ...TibcCoreRoutingV1MsgTypes,
  
])

export {
    Client,
    registry,
    MissingWalletError
}
