// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgAddSuper } from "./types/guardian/tx";
import { MsgDeleteSuper } from "./types/guardian/tx";

import { Super as typeSuper} from "./types"

export { MsgAddSuper, MsgDeleteSuper };

type sendMsgAddSuperParams = {
  value: MsgAddSuper,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteSuperParams = {
  value: MsgDeleteSuper,
  fee?: StdFee,
  memo?: string
};


type msgAddSuperParams = {
  value: MsgAddSuper,
};

type msgDeleteSuperParams = {
  value: MsgDeleteSuper,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgAddSuper({ value, fee, memo }: sendMsgAddSuperParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddSuper: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddSuper({ value: MsgAddSuper.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddSuper: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteSuper({ value, fee, memo }: sendMsgDeleteSuperParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteSuper: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeleteSuper({ value: MsgDeleteSuper.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteSuper: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgAddSuper({ value }: msgAddSuperParams): EncodeObject {
			try {
				return { typeUrl: "/petrihub.guardian.MsgAddSuper", value: MsgAddSuper.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddSuper: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteSuper({ value }: msgDeleteSuperParams): EncodeObject {
			try {
				return { typeUrl: "/petrihub.guardian.MsgDeleteSuper", value: MsgDeleteSuper.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteSuper: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Super: getStructure(typeSuper.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			PetrihubGuardian: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;