// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateHTLC } from "./types/htlc/tx";
import { MsgClaimHTLC } from "./types/htlc/tx";

import { HTLC as typeHTLC} from "./types"
import { AssetSupply as typeAssetSupply} from "./types"
import { Params as typeParams} from "./types"
import { AssetParam as typeAssetParam} from "./types"
import { SupplyLimit as typeSupplyLimit} from "./types"

export { MsgCreateHTLC, MsgClaimHTLC };

type sendMsgCreateHTLCParams = {
  value: MsgCreateHTLC,
  fee?: StdFee,
  memo?: string
};

type sendMsgClaimHTLCParams = {
  value: MsgClaimHTLC,
  fee?: StdFee,
  memo?: string
};


type msgCreateHTLCParams = {
  value: MsgCreateHTLC,
};

type msgClaimHTLCParams = {
  value: MsgClaimHTLC,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateHTLC({ value, fee, memo }: sendMsgCreateHTLCParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateHTLC: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateHTLC({ value: MsgCreateHTLC.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateHTLC: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgClaimHTLC({ value, fee, memo }: sendMsgClaimHTLCParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgClaimHTLC: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgClaimHTLC({ value: MsgClaimHTLC.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgClaimHTLC: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateHTLC({ value }: msgCreateHTLCParams): EncodeObject {
			try {
				return { typeUrl: "/petrimod.htlc.MsgCreateHTLC", value: MsgCreateHTLC.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateHTLC: Could not create message: ' + e.message)
			}
		},
		
		msgClaimHTLC({ value }: msgClaimHTLCParams): EncodeObject {
			try {
				return { typeUrl: "/petrimod.htlc.MsgClaimHTLC", value: MsgClaimHTLC.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgClaimHTLC: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						HTLC: getStructure(typeHTLC.fromPartial({})),
						AssetSupply: getStructure(typeAssetSupply.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						AssetParam: getStructure(typeAssetParam.fromPartial({})),
						SupplyLimit: getStructure(typeSupplyLimit.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			PetrimodHtlc: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;